name: 'Docker build configuration'
description: 'Prepare Docker build configuration for a specified app'
inputs:
  app:
    description: 'Excludes the following apps from the output (in comma-separated list format)'
    required: true
  config_file_path:
    description: 'The path to the configuration file.'
    required: true
    default: '.infrastructure/config.yaml'
  debug:
    description: 'Prints debug trace'
    required: true
    default: "false"
outputs:
  docker_registry:
    description: "The Docker registry for the specified app."
    value: ${{ steps.process.outputs.docker_registry }}
  docker_repository:
    description: "The Docker repository for the specified app."
    value: ${{ steps.process.outputs.docker_repository }}
  docker_repository_location_only:
    description: "The Docker repository location only(omits registry part) for the specified app."
    value: ${{ steps.process.outputs.docker_repository_location_only }}
  docker_image_tag:
    description: "The Docker image name for the current Git changeset."
    value: ${{ steps.process.outputs.docker_image_tag }}
  app_folder:
    description: "The folder of the specified app."
    value: ${{ steps.process.outputs.app_folder }}
runs:
  using: "composite"
  steps:
    - name: Read list of available apps
      id: process
      shell: bash
      env:
        CONFIG_PATH: ${{ inputs.config_file_path }}
        APP: ${{ inputs.app }}
        DEBUG: ${{ inputs.debug }}
      run: |
        set -e
        
        if [ "$DEBUG" == "true" ]; then
          set -x
          pwd
          find
        fi
        
        . ${{ github.action_path }}/../.scripts/docker-app-cfg.sh
        
        echo "::set-output name=docker_registry::$docker_registry"
        echo "::set-output name=docker_repository::$docker_repository"
        echo "::set-output name=docker_repository_location_only::$docker_repository_location_only"
        echo "::set-output name=docker_image::$docker_image"
        echo "::set-output name=docker_image_tag::$docker_image_tag"
        echo "::set-output name=app_folder::$app_folder"
