name: 'Deploy S3 artifact'
description: 'Deploy S3 distribution artifact'
inputs:
  config_file_path:
    description: 'The path to the configuration file.'
    required: true
    default: '.infrastructure/config.yaml'
  terragrunt_folder:
    description: 'The folder where Terragrunt is stored.'
    required: true
    default: '.infrastructure/terragrunt'
  app:
    description: 'The app to deploy'
    required: true
  account:
    description: 'The account to deploy in'
    required: true
  environment:
    description: 'The environment to deploy in'
    required: true
  changeset:
    description: 'The version to deploy'
    required: true
  debug:
    description: 'Prints debug trace'
    required: true
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Process
      id: process
      shell: bash
      env:
        CONFIG_PATH: ${{ inputs.config_file_path }}
        TERRAGRUNT_FOLDER: ${{ inputs.terragrunt_folder }}
        APP: ${{ inputs.app }}
        ENVIRONMENT: ${{ inputs.account }}-${{ inputs.environment }}
        CHANGESET: ${{ inputs.changeset }}
        DEBUG: ${{ inputs.debug }}
      run: |
        set -e
        
        if [ "$DEBUG" == "true" ]; then
          set -x
          pwd
          find
        fi
        
        source ${{ github.action_path }}/../.scripts/deploy-s3-artifact.sh
