name: 'Docker build and push apps'
description: 'Prepare Docker images and publish them for each app. Assumes that application is built and Dockerfiles manage the process of preparation of the image'
inputs:
  config_file_path:
    description: 'The path to the configuration file.'
    required: true
    default: '.infrastructure/config.yaml'
  exclude_apps:
    description: 'Excludes the following apps from the output (in comma-separated list format)'
    required: true
    default: common
  debug:
    description: 'Prints debug trace'
    required: true
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Read list of available apps
      id: process
      shell: bash
      env:
        CONFIG_PATH: ${{ inputs.config_file_path }}
        EXCLUDE_APPS: ${{ inputs.exclude_apps }}
        DEBUG: ${{ inputs.debug }}
      run: |
        set -e
        
        if [ "$DEBUG" == "true" ]; then
          set -x
          pwd
          find
        fi
        
        . ${{ github.action_path }}/../.scripts/docker-app-cfg.sh
        
